title: "Charlotte Private Soccer Training"
description: "One-on-one soccer training, small group training, and game analysis in Charlotte, NC."
url: "https://queencitystandouts.github.io"
baseurl: ""  # leave empty unless project is in subfolder

remote_theme: raviriley/agency-jekyll-theme
plugins:
  - jekyll-seo-tag
markdown: kramdown
